-- 날짜와 시간
SELECT SYSDATE FROM DUAL;

-- 날짜 시간 형식 변환
SELECT  TO_CHAR(SYSDATE, 'YYYY'),
        TO_CHAR(SYSDATE, 'MM'),
        TO_CHAR(SYSDATE, 'DD')
FROM DUAL;

-- 현재 날짜와 시간
SELECT SYSTIMESTAMP FROM DUAL;

-- 시간 형식 변환
SELECT  TO_CHAR(SYSDATE, 'HH:MI:SS'),
        TO_CHAR(SYSTIMESTAMP, 'YYYY/MM/DD HH:MI:SS')
FROM DUAL;

-- 10일을 더하고 빼기
SELECT SYSDATE +10 FROM DUAL;
SELECT SYSTIMESTAMP -10 FROM DUAL;

-- 특정 날짜에서 10일을 더하고 빼기
SELECT TO_DATE('2023/10/30') + 10 FROM DUAL;
SELECT TO_DATE('2023/10/30') - 10 FROM DUAL;

-- 월을 더하고 빼기
SELECT ADD_MONTHS(SYSDATE, +3) FROM DUAL;
SELECT ADD_MONTHS(SYSDATE, -3) FROM DUAL;
SELECT ADD_MONTHS(TO_DATE('2023/10/10'), 2) FROM DUAL;

-- 2023년부터 현재까지 총 개월 수 반올림
SELECT ROUND(MONTHS_BETWEEN(SYSDATE, TO_DATE('2023/1/1')), 0)
FROM DUAL;

-- 2023년부터 현재까지 총 개월 수 버림
SELECT ROUND(MONTHS_BETWEEN(SYSDATE, TO_DATE('2023/1/1')),0)
FROM DUAL;


