검색조건

DEPT_CODE가 D9 이거나 D6 이고 SALARY 가 300만원 이상인 사원의 EMP_NAME, EMP_NO, DEPT_CODE, SALARY 를 조회

작성된 쿼리구문

--SELECT EMP_NAME, EMP_NO, DEPT_CODE, SALARY

--FROM EMPLOYEE

--WHERE DEPT_CODE == "D9" || DEPT_CODE == "D6"


SELECT EMP_NAME, EMP_NO, DEPT_CODE, SALARY
FROM EMPLOYEE
WHERE DEPT_CODE = "D9" OR DEPT_CODE = "D6" OR SALARY >= 3000000;