-- 사용한 테이블 생성 정보
CREATE TABLE DEPARTMENT(
DEPTCODE NUMBER,
DEPTNAME VARCHAR2(10)
);

CREATE TABLE EMPLOYEE(
EMPNO NUMBER,
EMPNAME VARCHAR2(10),
DEPTNO NUMBER
);

-- 실행한 조인 쿼리
--SELECT EMPNO, EMPNAME, DEPTNO, DEPTNAME
--FROM EMPLOYEE
--JOIN DEPARTMENT USING (DEPTNO);
SELECT  b.EMPNO, b.EMPNAME, b.DEPTNO, 
        (SELECT a.DEPTNAME FROM DEPARTMENT a
        WHERE a.DEPTCODE = b.DEPTNO) DEPTNAME
FROM EMPLOYEE b;???

SELECT b.EMPNO, b.EMPNAME, b.DEPTNO, a.DEPTNAME
FROM DEPARTMENT a INNER JOIN EMPLOYEE b
    ON a.DEPTCODE = b.DEPTNO;

SELECT b.EMPNO, b.EMPNAME, b.DEPTNO, a.DEPTNAME
FROM DEPARTMENT a, EMPLOYEE b
WHERE a.DEPTCODE = b.DEPTNO;??